### ISSUE TITLE
Error in AI analysis: error loading config: no API keys provided

### ISSUE THREAD

**Issue by Shux1sh** [Zacarx/AICodeScan#3]
踩坑：
发现如果直接git clone把整个项目下载下来，然后重新编译的话config.yaml文件要这样写
```
api:
#  api接口base url
  url: "https://api.siliconflow.cn/v1/chat/completions"
#  密钥，最好参考api文档，以下是轨迹流动的api
  keys: 
    - sk-……
    - sk-……

settings:
#  每次调用ai间隔时间，防止频繁或者封号
  sleep_seconds: 3

model:
#  模型名称
  name: "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"

prompt:
  text: "请分析以下代码是否存在安全问题：\n文件: %s\n行号: %d\n内容:\n%s\n当前行：%s，请简明扼要，如果觉得大概率没有漏洞直接回答大概率没有漏洞七个汉字，如果有，严格按照一下格式输出：\n漏洞类型：\n危害等级：\n判断理由：\n可能的payload:"

```
具体原因是

![Image](https://github.com/user-attachments/assets/ffa86672-131b-4132-b14f-78e1b49c4c1e)
一开始以为是自己config.yaml路径问题，浪费时间有点久，希望别人二开工具的时候不会在这个坑上浪费时间。
